logging:
  level:
    com.projectlyrics.onboarding: debug
    org.hibernate.sql: debug

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
